"""Added some rows

Revision ID: 0e06c773e178
Revises: f5bff1d3eb49
Create Date: 2025-06-13 14:04:43.996571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e06c773e178'
down_revision = 'f5bff1d3eb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastoral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studentID', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('studentsInvolved', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('staffInvolved', sa.String(length=255), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target')
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastoral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', sa.VARCHAR(length=1), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('staffInvolved')
        batch_op.drop_column('studentsInvolved')
        batch_op.drop_column('location')
        batch_op.drop_column('time')
        batch_op.drop_column('date')
        batch_op.drop_column('studentID')
        pass
    # ### end Alembic commands ###
