"""Altered Caregiver Assoc table

Revision ID: 10e37464acde
Revises: d1302e974b6c
Create Date: 2025-06-20 16:56:31.471362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e37464acde'
down_revision = 'd1302e974b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alphanum', sa.String(length=2), nullable=False))
        batch_op.add_column(sa.Column('mobile_number', sa.String(length=20), nullable=False))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('home_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('work_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('phone_number')
        batch_op.drop_column('type')
        batch_op.drop_column('student_id')
        batch_op.drop_column('gender')
        batch_op.drop_column('dob')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mobile_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_level', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('year_level')
        batch_op.drop_column('mobile_number')
        batch_op.drop_column('preferred_name')

    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=1), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=1), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.INTEGER(), nullable=True))
        batch_op.alter_column('work_number',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('home_number',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('mobile_number')
        batch_op.drop_column('alphanum')

    # ### end Alembic commands ###
