"""Migrating with error fixes and updates to student class relationships

Revision ID: 143e7ceadd27
Revises: 
Create Date: 2025-05-25 20:35:45.848842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision = '143e7ceadd27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    if 'student_class' in inspector.get_table_names():
        op.drop_table('student_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_class',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('class_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'class_id')
    )
    # ### end Alembic commands ###
