"""Added the year columnd to the pastoral table

Revision ID: 1dbb79479328
Revises: 0e06c773e178
Create Date: 2025-06-16 16:22:43.309969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbb79479328'
down_revision = '0e06c773e178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('award', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('award', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
