"""Adding period class and connecting to classsession

Revision ID: 431770102678
Revises: 51b90a25eb83
Create Date: 2025-05-28 19:33:24.730273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431770102678'
down_revision = '51b90a25eb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_class_session_period_id', 'period', ['period_id'], ['id'])
        batch_op.drop_column('period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_constraint('fk_class_session_period_id', type_='foreignkey')
        batch_op.drop_column('period_id')

    # ### end Alembic commands ###
