"""Updated the User children models with method

Revision ID: 51b90a25eb83
Revises: 143e7ceadd27
Create Date: 2025-05-26 23:55:57.757352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b90a25eb83'
down_revision = '143e7ceadd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###
