"""Initial migration

Revision ID: 7f5ab3aae13a
Revises: 
Create Date: 2025-05-21 21:24:36.962778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5ab3aae13a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('author', sa.String(length=50), nullable=True))
        batch_op.alter_column('target_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('author')
        batch_op.drop_column('title')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
