"""Updatinf pastoral table

Revision ID: 91343aacc127
Revises: e7bc6a6ad70c
Create Date: 2025-06-22 16:36:21.568663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91343aacc127'
down_revision = 'e7bc6a6ad70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastoral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reportType', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('titleType', sa.String(length=50), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('studentID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastoral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studentID', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=1), nullable=True))
        batch_op.drop_column('titleType')
        batch_op.drop_column('student_id')
        batch_op.drop_column('reportType')

    # ### end Alembic commands ###
