"""updated models file for user, student, teacher and class creation

Revision ID: 92e212b814d4
Revises: 7f5ab3aae13a
Create Date: 2025-05-23 00:56:24.895165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e212b814d4'
down_revision = '7f5ab3aae13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('personal_email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('pe_name', ['personal_email'])
        batch_op.create_foreign_key('foreignKey_student_user_id', 'user', ['id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('class_id')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('foreignKey_teacher_user_id', 'user', ['id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('subject')
        batch_op.drop_column('main_class')
        batch_op.drop_column('sub_class')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('dob')
        batch_op.drop_column('school_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('dob', sa.DATETIME(), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
        batch_op.drop_column('role')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_class', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('main_class', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=1), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_name', type_='foreignkey')
        batch_op.drop_column('dob')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('f_name2', type_='foreignkey')
        batch_op.drop_constraint('name', type_='unique')
        batch_op.drop_column('personal_email')
        batch_op.drop_column('dob')

    op.create_table('classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
