"""a few column changes and population

Revision ID: 96af82d597c8
Revises: e7bc6a6ad70c
Create Date: 2025-06-23 14:14:48.724434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96af82d597c8'
down_revision = 'e7bc6a6ad70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.VARCHAR(length=1), nullable=True))

    # ### end Alembic commands ###
