"""Removed unnecessary columns from notice table

Revision ID: d33a99fd7909
Revises: 92e212b814d4
Create Date: 2025-05-23 11:57:20.010950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33a99fd7909'
down_revision = '92e212b814d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classes')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.create_table('classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
