"""added new model for schedule

Revision ID: d6affc4abf5e
Revises: f5bff1d3eb49
Create Date: 2025-06-16 09:35:59.781717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6affc4abf5e'
down_revision = 'f5bff1d3eb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_slot_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('SSI-FK-Name', 'schedule_slot', ['schedule_slot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('schedule_slot_id')

    # ### end Alembic commands ###
