"""Adding final columns to pastoral table

Revision ID: e8614d8c27ec
Revises: 91343aacc127
Create Date: 2025-06-23 09:54:25.566089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8614d8c27ec'
down_revision = '91343aacc127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastoral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentCommunication', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('disciplinaryActions', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resolutionStatus', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastoral', schema=None) as batch_op:
        batch_op.drop_column('resolutionStatus')
        batch_op.drop_column('disciplinaryActions')
        batch_op.drop_column('parentCommunication')

    # ### end Alembic commands ###
