"""Modified column in awards to get student_id

Revision ID: ee3cc81baaa3
Revises: 1dbb79479328
Create Date: 2025-06-17 17:10:57.189002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3cc81baaa3'
down_revision = '1dbb79479328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('award', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_award_student_id', 'student', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('award', schema=None) as batch_op:
        batch_op.drop_constraint('fk_award_student_id', type_='foreignkey')
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
